In [2]:
import numpy as np
import pandas as pd

In [7]:
a1= np.array ([[1,2,3.3],[4,5,6.3]])

In [8]:
a1

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [9]:
a1.shape

(2, 3)

In [10]:
a1.dtype

dtype('float64')

In [11]:
a1.ndim

2

In [12]:
a1.size

6

In [14]:
df = pd.DataFrame(a1)

In [15]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.3

In [3]:
r = np.random.rand(5)

In [4]:
r

array([0.748979  , 0.44300315, 0.38645301, 0.29956516, 0.18636579])

In [8]:
ran = np.random.rand(2,2,3)

In [9]:
ran

array([[[0.81087619, 0.29319649, 0.92650336],
        [0.6594624 , 0.30594368, 0.37688779]],

       [[0.02318572, 0.00743712, 0.86125989],
        [0.56716764, 0.0910004 , 0.27666412]]])

In [12]:
zeroes = np.zeros((2,2))
zeroes

array([[0., 0.],
       [0., 0.]])

In [15]:
full = np.full((3,3,2), 5)
full

array([[[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]]])

In [17]:
ones = np.ones((2,3,2))
ones

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [20]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
rand_int = np.random.randint(1,10,2)
rand_int

array([3, 8])

In [23]:
rand_int1 = np.random.randint(1,10, size=(3,2))
rand_int1

array([[5, 1],
       [6, 3],
       [6, 8]])

In [36]:
np.random.seed(2)
rand_int2=np.random.randint(10, size=(4,4))
rand_int2

array([[8, 8, 6, 2],
       [8, 7, 2, 1],
       [5, 4, 4, 5],
       [7, 3, 6, 4]])

In [37]:
np.unique(rand_int2)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
rand_int2[1,0]

8

In [39]:
rand_int2[:2]

array([[8, 8, 6, 2],
       [8, 7, 2, 1]])

In [40]:
rand_int2[:2,:1]

array([[8],
       [8]])

In [42]:
arr1= np.array([2,4,6])
arr2= np.array([3,6,9])

In [43]:
arr1

array([2, 4, 6])

In [44]:
arr2

array([3, 6, 9])

In [54]:
#addition with add
add_arr = np.add(arr1,arr2)
add_arr

array([ 5, 10, 15])

In [55]:
#addition with + sign
addition_arr = arr1+arr2
addition_arr

array([ 5, 10, 15])

In [56]:
#summation 
sum_arr = np.sum([arr1,arr2])
sum_arr

30

In [57]:
#summation over axis 1(rowwise or self add)
sum_arr_axis1 = np.sum([arr1,arr2], axis=1)
sum_arr_axis1

array([12, 18])

In [58]:
#summation over axis 0 (columnwise or like add)
sum_arr_axis0 = np.sum([arr1,arr2], axis=0)
sum_arr_axis0

array([ 5, 10, 15])

In [61]:
# subtraction with subtract
sub_arr = np.subtract(arr1,arr2)
sub_arr

array([-1, -2, -3])

In [62]:
#subtraction by - sign
subtract_arr = arr2 - arr1
subtract_arr

array([1, 2, 3])

In [64]:
arr1

array([2, 4, 6])

In [63]:
# discrite difference
diff = np.diff(arr1)
diff

array([2, 2])

In [74]:
#random integer array creation with randint 
#seed used to keep randint constant
np.random.seed(12)
arr3 = np.random.randint(1,10,size=(1,3))
arr3

array([[7, 2, 3]])

In [73]:
# discrite differnece with n 
diff = np.diff(arr3, n=2)
diff

array([[6]])

In [75]:
#multiplication with multiply
mul_arr = np.multiply(arr1,arr2)
mul_arr

array([ 6, 24, 54])

In [81]:
# multiplication with * sign
mult_arr = arr1*arr2
mult_arr

array([ 6, 24, 54])

In [84]:
#Product
prod = np.prod(arr1)
product = np.prod([arr1,arr2])
prod
product

7776

In [94]:
arr4 = np.array([8,16,24,32,40])
arr5 = np.array([2,3,4,5,6])
arr4

array([ 8, 16, 24, 32, 40])

In [95]:
arr5

array([2, 3, 4, 5, 6])

In [96]:
#Divide
div =np.divide(arr4,arr5)
div

array([4.        , 5.33333333, 6.        , 6.4       , 6.66666667])

In [97]:
#Remainder by mod
mod = np.mod(arr4,arr5)
mod

array([0, 1, 0, 2, 4])

In [98]:
# Remainder by remainder
remain = np.remainder(arr4,arr5)
remain

array([0, 1, 0, 2, 4])

In [99]:
#Quotient and mod 
qm = np.divmod(arr4,arr5)
qm

(array([4, 5, 6, 6, 6]), array([0, 1, 0, 2, 4]))

In [101]:
arr1,arr2

(array([2, 4, 6]), array([3, 6, 9]))

In [103]:
# Power 
power = np.power(arr1,arr2)
power

array([       8,     4096, 10077696])

In [104]:
# Absolute
arr7 = np.array([-8,-5,7,9,-2,0,-1])
abs = np.absolute(arr7)
abs

array([8, 5, 7, 9, 2, 0, 1])